import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import io
import guitarpro
from app.transcription.gp_generator import generate_gp5

# Mock some notes
test_notes = [
    {"pitch": "E3", "midi": 52, "start_time": 0.0, "duration": 1.0, "string": 4, "fret": 2},
    {"pitch": "G3", "midi": 55, "start_time": 1.0, "duration": 1.0, "string": 3, "fret": 0},
    {"pitch": "B3", "midi": 59, "start_time": 2.0, "duration": 1.0, "string": 2, "fret": 0},
]

try:
    print("Generating GP5...")
    gp5_data = generate_gp5(test_notes, title="Test Scale", bpm=120)
    print("Generated bytes length:", len(gp5_data))
    
    # Try parsing it back using guitarpro
    print("Parsing GP5 back...")
    song = guitarpro.parse(io.BytesIO(gp5_data))
    print("Successfully parsed GP5!")
    print("Song Title:", song.title)
    print("Track Name:", song.tracks[0].name)
    print("Measures Count:", len(song.tracks[0].measures))
    for m in song.tracks[0].measures:
        print(f"Measure {m.number} beats:")
        for b in m.voices[0].beats:
            print(f"  Beat status: {b.status}, notes: {[n.value for n in b.notes]} on strings {[n.string for n in b.notes]}")
except Exception as e:
    print("ERROR DURING GENERATING OR PARSING:", e)
    import traceback
    traceback.print_exc()
